spring.application.name=info

# ===============================
# DATABASE - JPA
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/inventariodb
spring.datasource.username=dev
spring.datasource.password=dev123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# CLAVES
# ===============================
jwt.secret=mi_clave_super_segura_12345678901234567890

# ===============================
# TOKEN
# ==============================
jwt.access-exp-ms=3600000
jwt.refresh-exp-ms=604800000
