spring.application.name=info

# ===============================
# ORIGEN
# ==============================
app.cors.origins:http://localhost:4200,http://3.134.53.31
# ===============================
# DATABASE - JPA
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/inventariodb
spring.datasource.username=dev
spring.datasource.password=dev123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# ===============================
# SAVE DOCUMENTS
# ===============================
app.uploads.base-path=/app/uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# CLAVES
# ===============================
jwt.secret=mi_clave_super_segura_12345678901234567890

# ===============================
# TOKEN
# ==============================
jwt.access-exp-ms=3600000
jwt.refresh-exp-ms=604800000

# ===============================
# SWAGGER
# ==============================
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
