spring.application.name=mss_api

# ===============================
# DATABASE - JPA
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/mss_sfs_db
spring.datasource.username=dev
spring.datasource.password=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# CLAVES
# ===============================
jwt.secret=mi_clave_super_segura_12345678901234567890

# ===============================
# TOKEN
# ==============================
jwt.access-exp-ms=3600000
jwt.refresh-exp-ms=604800000
